// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package rexTypes

type AllowCreateModelIndustry struct {
	Name              string `json:"name"`                        // 名称
	Qualification     string `json:"qualification"`               // 资质要求
	QualificationLink string `json:"qualification_link,optional"` // 资质要求，法律依据及示例的说明链接
	CategoryScope     string `json:"category_scope"`              // 类目适用范围
	Remark            string `json:"remark,optional"`             // 备注
	ParentId          uint32 `json:"parent_id,optional"`
	Sort              int64  `json:"sort,optional"`
}

type AllowCreateModelShortLink struct {
	OriginalUrl   string `json:"original_url"`
	SlType        int32  `json:"sl_type,optional,options=1|2|3"`
	ExpireAtUnix  int64  `json:"expire_at_unix,optional"`
	CreatorUserId string `json:"creator_user_id,optional"`
}

type AllowCreateModelTag struct {
	Name string `json:"name"`
	Sort int64  `json:"sort"`
}

type AllowUpdateModelIndustry struct {
	Id                uint32 `json:"id"`
	Name              string `json:"name,optional"`           // 名称
	Qualification     string `json:"qualification,optional"`  // 资质要求
	QualificationLink string `json:"qualification_link"`      // 资质要求，法律依据及示例的说明链接
	CategoryScope     string `json:"category_scope,optional"` // 类目适用范围
	Remark            string `json:"remark"`                  // 备注
	ParentId          uint32 `json:"parent_id"`
	Sort              int64  `json:"sort,optional"`
}

type AllowUpdateModelShortLink struct {
	Id            uint32 `json:"id"`
	OriginalUrl   string `json:"original_url,optional"`
	SlType        int32  `json:"sl_type,optional,options=1|2|3"`
	ExpireAtUnix  int64  `json:"expire_at_unix"`
	CreatorUserId string `json:"creator_user_id"`
}

type AllowUpdateModelTag struct {
	Id   uint32 `json:"id"`
	Name string `json:"name,optional"`
	Sort int64  `json:"sort,optional"`
}

type AllowUpdateStatusModelIndustry struct {
	Id     uint32 `json:"id"`
	Status int32  `json:"status"`
}

type AllowUpdateStatusModelShortLink struct {
	Id     uint32 `json:"id"`
	Status int32  `json:"status"`
}

type AllowUpdateStatusModelTag struct {
	Id     uint32 `json:"id"`
	Status int32  `json:"status"`
}

type ApiCaptchaGenerateReq struct {
	Key       string  `json:"key,optional"`
	DotCount  int32   `json:"dot_count,optional"`
	MaxSkew   float64 `json:"max_skew,optional"`
	KeyLong   int32   `json:"key_long,optional"`
	ImgWidth  int32   `json:"img_width,optional"`
	ImgHeight int32   `json:"img_height,optional"`
}

type ApiCaptchaGenerateResp struct {
	Key     string `json:"key,omitempty"`
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type ApiCaptchaGenerateRespData struct {
	Key     string `json:"key,omitempty"`
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type ApiSmsSendReq struct {
	Key    string   `json:"key"`
	Mobile string   `json:"mobile"`
	Params []string `json:"params,optional"`
}

type ApiSmsSendResp struct {
	RequestID string `json:"requestId"`
}

type BehavioralVerificationInitReq struct {
	Key     string `json:"key"`
	Service string `json:"service"`
	Type    string `json:"type"`
}

type BehavioralVerificationInitResp struct {
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type BehavioralVerificationVerifyReq struct {
	Id         string `json:"id"`
	Service    string `json:"service"`
	Type       string `json:"type"`
	VerifyCode string `json:"verify_code"`
}

type BehavioralVerificationVerifyResp struct {
	Result bool `json:"result"`
}

type BootstrapReq struct {
	AccessKey    string `form:"access_key"`
	AccessSecret string `form:"access_secret"`
}

type BootstrapResp struct {
}

type CodesReq struct {
	Lang string `form:"lang,optional" url:"lang"`
	Svc  string `form:"svc,optional" url:"svc"`
}

type CodesResp struct {
	List     []ModelCode `json:"list"`
	Total    int64       `json:"total"`
	Page     int32       `json:"page"`
	PageSize int32       `json:"page_size"`
}

type CreateExistBucketAndConfigReq struct {
	ConfigKey    string `json:"config_key"`
	StorageType  string `json:"storage_type"`
	AppId        string `json:"app_id,optional"`
	AccessKey    string `json:"access_key"`
	AccessSecret string `json:"access_secret"`
	BucketKey    string `json:"bucket_key"`
	Name         string `json:"name"`
	Region       string `json:"region"`
	IsAccelerate int32  `json:"is_accelerate"`
	Prefix       string `json:"prefix"`
	StaticDomain string `json:"static_domain"`
	CdnDomain    string `json:"cdn_domain"`
}

type CreateExistBucketAndConfigResp struct {
}

type CreateExistBucketNoConfigReq struct {
	ConfigKey    string `json:"config_key"`
	BucketKey    string `json:"bucket_key"`
	Name         string `json:"name"`
	Region       string `json:"region"`
	IsAccelerate int32  `json:"is_accelerate"`
	Prefix       string `json:"prefix"`
	StaticDomain string `json:"static_domain"`
	CdnDomain    string `json:"cdn_domain"`
}

type CreateExistBucketNoConfigResp struct {
}

type EncryptReq struct {
	Data string `json:"data"`
}

type EncryptResp struct {
	Data string `json:"data"`
}

type GetRedirectResultReq struct {
	ShortId string `json:"short_id"`
}

type GetRedirectResultResp struct {
	Url string `json:"url"`
}

type HealthzResp struct {
}

type IndustryApiCreateResp struct {
	Id uint32 `json:"id"`
}

type IndustryApiFormIdReq struct {
	Id uint32 `form:"id"`
}

type IndustryApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type IndustryApiJsonIdsReq struct {
	Ids []uint32 `json:"ids"`
}

type IndustryApiOKResp struct {
}

type IndustryCommonQueryListResp struct {
	List     []ModelIndustry `json:"list"`
	Total    int64           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type IndustryCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int32  `json:"status,optional"`
	ParentId       uint32 `json:"parent_id,optional"`
	OnlyParent     bool   `json:"only_parent,optional"` // 是否只查询父级行业
}

type IpWhiteReq struct {
	AccessKey string `json:"access_key"`
	Ip        string `json:"ip"`
	Remark    string `json:"remark"`
}

type IpWhiteResp struct {
}

type KmsAkcCreateKeychainReq struct {
	CertType string `json:"cert_type"`
	Name     string `json:"name"`
}

type KmsAkcCreateKeychainResp struct {
	Status     string `json:"status"`
	Name       string `json:"name"`
	SignMethod string `json:"sign_method"`
	CertType   string `json:"cert_type"`
	PublicKey  string `json:"public_key"`
}

type KmsAkcGetKeychainPublicKeyReq struct {
	Name string `json:"name"`
}

type KmsAkcGetKeychainPublicKeyResp struct {
	Name       string `json:"name"`
	SignMethod string `json:"sign_method"`
	CertType   string `json:"cert_type"`
	PublicKey  string `json:"public_key"`
}

type KmsAkcSignReq struct {
	Name        string `json:"name"`
	SignContent string `json:"sign_content"`
}

type KmsAkcSignResp struct {
	Name string `json:"name"`
	Sign string `json:"sign"`
}

type KmsAkcVerifyReq struct {
	Name        string `json:"name"`
	SignContent string `json:"sign_content"`
	Sign        string `json:"sign"`
}

type KmsAkcVerifyResp struct {
	Name   string `json:"name"`
	Verify bool   `json:"verify"`
}

type KmsSkcBatchDecryptReq struct {
	Data map[string]KmsSkcBatchDecryptReqItem `json:"data"`
}

type KmsSkcBatchDecryptReqItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcBatchDecryptResp struct {
	Data map[string]KmsSkcBatchDecryptRespItem `json:"data"`
}

type KmsSkcBatchDecryptRespItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcBatchEncryptReq struct {
	Data map[string]KmsSkcBatchEncryptReqItem `json:"data"`
}

type KmsSkcBatchEncryptReqItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcBatchEncryptResp struct {
	Data map[string]KmsSkcBatchEncryptRespItem `json:"data"`
}

type KmsSkcBatchEncryptRespItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcCompareItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcCompareReq struct {
	List []KmsSkcCompareItem `json:"list"`
}

type KmsSkcCompareResp struct {
	Status      string                      `json:"status"`
	CompareData bool                        `json:"compare_data"`
	List        []KmsSkcCompareRespDataItem `json:"list"`
}

type KmsSkcCompareRespData struct {
	Status      string                      `json:"status"`
	CompareData bool                        `json:"compare_data"`
	List        []KmsSkcCompareRespDataItem `json:"list"`
}

type KmsSkcCompareRespDataItem struct {
	Status   string `json:"status"`
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcCreateKeychainReq struct {
	Algorithm string `json:"algorithm"`
	Name      string `json:"name"`
}

type KmsSkcCreateKeychainResp struct {
	Status string `json:"status"`
	Name   string `json:"name"`
}

type KmsSkcDecryptReq struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcDecryptResp struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcEncryptReq struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcEncryptResp struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type ModelCode struct {
	Code string `json:"code"`
	Num  int32  `json:"num"`
	Msg  string `json:"msg"`
}

type ModelIndustry struct {
	Id                uint32 `json:"id"`
	CreatedAtUnix     int64  `json:"created_at_unix"`
	UpdatedAtUnix     int64  `json:"updated_at_unix"`
	Status            int32  `json:"status"`             // 状态
	Name              string `json:"name"`               // 名称
	Qualification     string `json:"qualification"`      // 资质要求
	QualificationLink string `json:"qualification_link"` // 资质要求，法律依据及示例的说明链接
	CategoryScope     string `json:"category_scope"`     // 类目适用范围
	Remark            string `json:"remark"`             // 备注
	ParentId          uint32 `json:"parent_id"`
	Sort              int64  `json:"sort"`
}

type ModelShortLink struct {
	Id            uint32 `json:"id"`
	CreatedAtUnix int64  `json:"created_at_unix"`
	UpdatedAtUnix int64  `json:"updated_at_unix"`
	Key           string `json:"key"`
	OriginalUrl   string `json:"original_url"`
	SlType        int32  `json:"sl_type"`
	ExpireAtUnix  int64  `json:"expire_at_unix"`
	CreatorUserId string `json:"creator_user_id"`
}

type ModelTag struct {
	Id            uint32 `json:"id"`
	CreatedAtUnix int64  `json:"created_at_unix"`
	UpdatedAtUnix int64  `json:"updated_at_unix"`
	Name          string `json:"name"`   // 标签名称
	Status        int32  `json:"status"` // 状态
	Sort          int64  `json:"sort"`
}

type ModelZone struct {
	Label string `json:"label"`
	Code  string `json:"code"`
	Area  string `json:"area"`
}

type NotFoundResp struct {
}

type NotFoundpReq struct {
}

type SasPresignerGetObjectReq struct {
	BucketKey string `json:"bucket_key"`
	Path      string `json:"path"`
}

type SasPresignerGetObjectResp struct {
	Url    string `json:"url"`
	Method string `json:"method"`
}

type SasPresignerHeadObjectReq struct {
	BucketKey string `json:"bucket_key"`
	Path      string `json:"path"`
}

type SasPresignerHeadObjectResp struct {
	Url    string `json:"url"`
	Method string `json:"method"`
}

type SasPresignerUploadReq struct {
	BucketKey string `json:"bucket_key"`
	Path      string `json:"path"`
}

type SasPresignerUploadResp struct {
	Url    string            `json:"url"`
	Fields map[string]string `json:"fields"`
}

type SasQueryBucketReq struct {
	BucketKey string `json:"bucket_key"`
}

type SasQueryBucketResp struct {
	Name                   string `json:"name"`
	Prefix                 string `json:"prefix"`
	Region                 string `json:"region"`
	BucketInternetDomain   string `json:"bucket_internet_domain"`
	BucketInternalDomain   string `json:"bucket_internal_domain"`
	IsAccelerate           int32  `json:"is_accelerate"`
	BucketAccelerateDomain string `json:"bucket_accelerate_domain"`
	StaticDomain           string `json:"static_domain"`
	CdnDomain              string `json:"cdn_domain"`
}

type ShortLinkApiCreateResp struct {
	Id      uint32 `json:"id"`
	ShortId string `json:"short_id"`
}

type ShortLinkApiFormIdReq struct {
	Id uint32 `form:"id"`
}

type ShortLinkApiFormKeyReq struct {
	Key string `form:"key"`
}

type ShortLinkApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type ShortLinkApiJsonIdsReq struct {
	Ids []uint32 `json:"ids"`
}

type ShortLinkApiOKResp struct {
}

type ShortLinkCommonQueryListResp struct {
	List     []ModelShortLink `json:"list"`
	Total    int64            `json:"total"`
	Page     int32            `json:"page"`
	PageSize int32            `json:"page_size"`
}

type ShortLinkCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int32  `json:"status,optional"`
}

type SmsInitReq struct {
	Key     string `json:"key"`
	Service string `json:"service"`
	Type    string `json:"type"`
	Zone    string `json:"zone"`
	Phone   string `json:"phone"`
}

type SmsInitResp struct {
	Status string `json:"status"`
}

type SmsVerifyReq struct {
	Service    string `json:"service"`
	Type       string `json:"type"`
	Zone       string `json:"zone"`
	Phone      string `json:"phone"`
	VerifyCode string `json:"verify_code"`
}

type SmsVerifyResp struct {
	Result bool `json:"result"`
}

type TagApiCreateResp struct {
	Id uint32 `json:"id"`
}

type TagApiFormIdReq struct {
	Id uint32 `form:"id"`
}

type TagApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type TagApiJsonIdsReq struct {
	Ids []uint32 `json:"ids"`
}

type TagApiOKResp struct {
}

type TagCommonQueryListResp struct {
	List     []ModelTag `json:"list"`
	Total    int64      `json:"total"`
	Page     int32      `json:"page"`
	PageSize int32      `json:"page_size"`
}

type TagCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int32  `json:"status,optional"`
	PrefixKeyword  string `json:"prefix_keyword,optional"`
}

type TpasWechatJobWebhookReq struct {
	Timestamp int64  `json:"timestamp"`
	Nonce     string `json:"nonce"` // 随机字符串
	Params    string `json:"params"`
}

type TpasWechatJobWebhookResp struct {
}

type UpsBaseBootstrapReq struct {
}

type UpsBaseBootstrapResp struct {
}

type ViewNotFoundReq struct {
}

type ViewNotFoundResp struct {
}

type ViewShortLinkReq struct {
	DomainId string `path:"domain_id"`
	ShortId  string `path:"short_id"`
}

type ViewShortLinkResp struct {
}

type ZonesReq struct {
	Lang string `form:"lang,optional" url:"lang"`
}

type ZonesResp struct {
	List     []ModelZone `json:"list"`
	Total    int64       `json:"total"`
	Page     int32       `json:"page"`
	PageSize int32       `json:"page_size"`
}
