// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package rexTypes

type AddSomePolicyReq struct {
	Subject string `json:"subject"`
	Object  string `json:"object"`
	Action  string `json:"action"`
}

type AllowCreateModelBucketConfig struct {
	Name         string `json:"name"`
	StorageType  string `json:"storage_type,options=minio|cos|oss|s3|obs"`
	CredentialID int64  `json:"credential_id"`
	BucketName   string `json:"bucket_name"`
	Region       string `json:"region"`
	Prefix       string `json:"prefix"`
	Endpoint     string `json:"endpoint"`
	PublicDomain string `json:"public_domain"`
	Remark       string `json:"remark,optional"`
}

type AllowCreateModelCaptchaConfig struct {
	Name      string  `json:"name"`
	DotCount  int32   `json:"dot_count"`
	MaxSkew   float64 `json:"max_skew"`
	KeyLong   int32   `json:"key_long"`
	ImgWidth  int32   `json:"img_width"`
	ImgHeight int32   `json:"img_height"`
}

type AllowCreateModelCredential struct {
	Name            string `json:"name"`
	CredentialType  string `json:"credential_type,options=aliyun|tencent_cloud|huawei_cloud|email|wechat_offiaccount|aws"`
	AccessKeyID     string `json:"access_key_id"`
	SecretAccessKey string `json:"secret_access_key"`
	Remark          string `json:"remark"`
	DefaultRegion   string `json:"default_region"`
	AppID           string `json:"app_id"`
	Endpoint        string `json:"endpoint"`
}

type AllowCreateModelEmsConfig struct {
	Name         string `json:"name"`
	CredentialID int64  `json:"credential_id"`
	SenderName   string `json:"sender_name"`
	Endpoint     string `json:"endpoint"`
	Port         int32  `json:"port"`
	Protocol     string `json:"protocol"`
	Remark       string `json:"remark,optional"`
}

type AllowCreateModelSmsConfig struct {
	Name         string `json:"name"`
	CredentialID int64  `json:"credential_id"`
	Endpoint     string `json:"endpoint"`
	Template     string `json:"template"`
	SignName     string `json:"sign_name"`
	ParamsStr    string `json:"params_str"`
	Remark       string `json:"remark,optional"`
}

type AllowCreateModelWechatConfig struct {
	Name         string `json:"name"`
	AppType      string `json:"app_type,options=official|mini_app"`
	CredentialID int64  `json:"credential_id"`
	GhId         string `json:"gh_id"`
	AppName      string `json:"app_name"`
	Remark       string `json:"remark,optional"`
}

type AllowUpdateDefaultModelBucketConfig struct {
	Id int64 `json:"id"`
}

type AllowUpdateDefaultModelCaptchaConfig struct {
	Id int64 `json:"id"`
}

type AllowUpdateDefaultModelCredential struct {
	Id int64 `json:"id"`
}

type AllowUpdateDefaultModelEmsConfig struct {
	Id int64 `json:"id"`
}

type AllowUpdateDefaultModelSmsConfig struct {
	Id int64 `json:"id"`
}

type AllowUpdateDefaultModelWechatConfig struct {
	Id int64 `json:"id"`
}

type AllowUpdateModelBucketConfig struct {
	Id           int64  `json:"id"`
	Name         string `json:"name,optional"`
	StorageType  string `json:"storage_type,optional,options=minio|cos|oss|s3|obs"`
	CredentialID int64  `json:"credential_id,optional"`
	BucketName   string `json:"bucket_name,optional"`
	Region       string `json:"region,optional"`
	Prefix       string `json:"prefix,optional"`
	Endpoint     string `json:"endpoint,optional"`
	PublicDomain string `json:"public_domain,optional"`
	Remark       string `json:"remark"`
}

type AllowUpdateModelCaptchaConfig struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name,optional"`
	DotCount  int32   `json:"dot_count,optional"`
	MaxSkew   float64 `json:"max_skew,optional"`
	KeyLong   int32   `json:"key_long,optional"`
	ImgWidth  int32   `json:"img_width,optional"`
	ImgHeight int32   `json:"img_height,optional"`
}

type AllowUpdateModelCredential struct {
	Id              int64  `json:"id"`
	Name            string `json:"name,optional"`
	CredentialType  string `json:"credential_type,optional,options=aliyun|tencent_cloud|huawei_cloud|email|wechat_offiaccount|aws"`
	AccessKeyID     string `json:"access_key_id,optional"`
	SecretAccessKey string `json:"secret_access_key,optional"`
	Remark          string `json:"remark"`
	DefaultRegion   string `json:"default_region"`
	AppID           string `json:"app_id"`
	Endpoint        string `json:"endpoint"`
}

type AllowUpdateModelEmsConfig struct {
	Id           int64  `json:"id"`
	Name         string `json:"name,optional"`
	CredentialID int64  `json:"credential_id,optional"`
	SenderName   string `json:"sender_name,optional"`
	Endpoint     string `json:"endpoint,optional"`
	Port         int32  `json:"port,optional"`
	Protocol     string `json:"protocol,optional"`
	Remark       string `json:"remark"`
}

type AllowUpdateModelSmsConfig struct {
	Id           int64  `json:"id"`
	Name         string `json:"name,optional"`
	CredentialID int64  `json:"credential_id,optional"`
	Endpoint     string `json:"endpoint,optional"`
	Template     string `json:"template,optional"`
	SignName     string `json:"sign_name,optional"`
	ParamsStr    string `json:"params_str,optional"`
	Remark       string `json:"remark"`
}

type AllowUpdateModelWechatConfig struct {
	Id           int64  `json:"id"`
	Name         string `json:"name,optional"`
	AppType      string `json:"app_type,options=official|mini_app,optional"`
	CredentialID int64  `json:"credential_id,optional"`
	GhId         string `json:"gh_id,optional"`
	AppName      string `json:"app_name,optional"`
	Remark       string `json:"remark"`
}

type AllowUpdateStatusModelBucketConfig struct {
	Id     int64 `json:"id"`
	Status int16 `json:"status"`
}

type AllowUpdateStatusModelCaptchaConfig struct {
	Id     int64 `json:"id"`
	Status int16 `json:"status"`
}

type AllowUpdateStatusModelCredential struct {
	Id     int64 `json:"id"`
	Status int16 `json:"status"`
}

type AllowUpdateStatusModelEmsConfig struct {
	Id     int64 `json:"id"`
	Status int16 `json:"status"`
}

type AllowUpdateStatusModelSmsConfig struct {
	Id     int64 `json:"id"`
	Status int16 `json:"status"`
}

type AllowUpdateStatusModelWechatConfig struct {
	Id     int64 `json:"id"`
	Status int16 `json:"status"`
}

type ApiCaptchaGenerateReq struct {
	Key       string  `json:"key,optional"`
	DotCount  int32   `json:"dot_count,optional"`
	MaxSkew   float64 `json:"max_skew,optional"`
	KeyLong   int32   `json:"key_long,optional"`
	ImgWidth  int32   `json:"img_width,optional"`
	ImgHeight int32   `json:"img_height,optional"`
}

type ApiCaptchaGenerateResp struct {
	Key     string `json:"key,optional,omitempty"`
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type ApiCaptchaGenerateRespData struct {
	Key     string `json:"key,optional,omitempty"`
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type ApiEmsCheckReq struct {
	RequestId string `json:"request_id"`
}

type ApiEmsCheckResp struct {
	RequestId string `json:"request_id"`
	Status    int16  `json:"status"`
	Code      string `json:"code"`
	Message   string `json:"message"`
}

type ApiEmsSendReq struct {
	Name           string            `json:"name,optional"`
	Service        string            `json:"service,optional"`
	Scene          string            `json:"scene,optional"`
	RecipientEmail []string          `json:"recipient_email"`
	Cc             []ApiEmsSendReqCc `json:"cc,optional"`
	Subject        string            `json:"subject"`
	SendType       string            `json:"send_type"`
	SendBody       string            `json:"send_body"`
}

type ApiEmsSendReqCc struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type ApiEmsSendResp struct {
	RequestId string `json:"request_id"`
}

type ApiEmsSendSyncResp struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

type ApiSmsCheckReq struct {
	RequestId string `json:"request_id"`
}

type ApiSmsCheckResp struct {
	RequestId string `json:"request_id"`
	Status    int16  `json:"status"`
	Code      string `json:"code"`
	Message   string `json:"message"`
}

type ApiSmsSendReq struct {
	Name    string   `json:"name,optional"`
	Zone    string   `json:"zone,optional"`
	Mobile  string   `json:"mobile"`
	Params  []string `json:"params,optional"`
	Service string   `json:"service,optional"`
	Scene   string   `json:"scene,optional"`
}

type ApiSmsSendResp struct {
	RequestId string `json:"request_id"`
}

type ApiSmsSendSyncResp struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

type BehavioralVerificationInitReq struct {
	Key     string `json:"key,optional"`
	Service string `json:"service"`
	Type    string `json:"type"`
}

type BehavioralVerificationInitResp struct {
	RequestId string `json:"request_id"`
	Id        string `json:"id,omitempty"`
	Content   string `json:"content,omitempty"`
	Answer    string `json:"answer,omitempty"`
	Img       string `json:"img,omitempty"`
}

type BehavioralVerificationVerifyReq struct {
	Id         string `json:"id"`
	Service    string `json:"service"`
	Type       string `json:"type"`
	VerifyCode string `json:"verify_code"`
}

type BehavioralVerificationVerifyResp struct {
	Result  bool   `json:"result"`
	Code    string `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}

type BucketConfigApiCreateResp struct {
	Id int64 `json:"id"`
}

type BucketConfigApiFormIdReq struct {
	Id int64 `form:"id"`
}

type BucketConfigApiFormIdsReq struct {
	Ids []int64 `form:"ids"`
}

type BucketConfigApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type BucketConfigApiJsonIdsReq struct {
	Ids []int64 `json:"ids"`
}

type BucketConfigApiOKResp struct {
}

type BucketConfigCommonQueryListResp struct {
	List     []ModelBucketConfig `json:"list"`
	Total    int64               `json:"total"`
	Page     int32               `json:"page"`
	PageSize int32               `json:"page_size"`
}

type BucketConfigCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int16  `json:"status,optional"`
}

type CaptchaConfigApiCreateResp struct {
	Id int64 `json:"id"`
}

type CaptchaConfigApiFormIdReq struct {
	Id int64 `form:"id"`
}

type CaptchaConfigApiFormIdsReq struct {
	Ids []int64 `form:"ids"`
}

type CaptchaConfigApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type CaptchaConfigApiJsonIdsReq struct {
	Ids []int64 `json:"ids"`
}

type CaptchaConfigApiOKResp struct {
}

type CaptchaConfigCommonQueryListResp struct {
	List     []ModelCaptchaConfig `json:"list"`
	Total    int64                `json:"total"`
	Page     int32                `json:"page"`
	PageSize int32                `json:"page_size"`
}

type CaptchaConfigCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int16  `json:"status,optional"`
}

type CodesReq struct {
	Lang string `form:"lang,optional" url:"lang"`
	Svc  string `form:"svc,optional" url:"svc"`
}

type CodesResp struct {
	List     []ModelCode `json:"list"`
	Total    int64       `json:"total"`
	Page     int32       `json:"page"`
	PageSize int32       `json:"page_size"`
}

type CreateExistBucketAndConfigReq struct {
	ConfigKey    string `json:"config_key,optional"`
	StorageType  string `json:"storage_type"`
	AppId        string `json:"app_id,optional"`
	AccessKey    string `json:"access_key"`
	AccessSecret string `json:"access_secret"`
	BucketKey    string `json:"bucket_key,optional"`
	Name         string `json:"name"`
	Region       string `json:"region"`
	IsAccelerate int32  `json:"is_accelerate"`
	Prefix       string `json:"prefix"`
	StaticDomain string `json:"static_domain"`
	CdnDomain    string `json:"cdn_domain"`
}

type CreateExistBucketAndConfigResp struct {
}

type CreateExistBucketNoConfigReq struct {
	ConfigKey    string `json:"config_key,optional"`
	BucketKey    string `json:"bucket_key,optional"`
	Name         string `json:"name"`
	Region       string `json:"region"`
	IsAccelerate int32  `json:"is_accelerate"`
	Prefix       string `json:"prefix"`
	StaticDomain string `json:"static_domain"`
	CdnDomain    string `json:"cdn_domain"`
}

type CreateExistBucketNoConfigResp struct {
}

type CredentialApiCreateResp struct {
	Id int64 `json:"id"`
}

type CredentialApiFormIdReq struct {
	Id int64 `form:"id"`
}

type CredentialApiFormIdsReq struct {
	Ids []int64 `form:"ids"`
}

type CredentialApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type CredentialApiJsonIdsReq struct {
	Ids []int64 `json:"ids"`
}

type CredentialApiOKResp struct {
}

type CredentialCommonQueryListResp struct {
	List     []ModelCredential `json:"list"`
	Total    int64             `json:"total"`
	Page     int32             `json:"page"`
	PageSize int32             `json:"page_size"`
}

type CredentialCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int16  `json:"status,optional"`
}

type EmsConfigApiCreateResp struct {
	Id int64 `json:"id"`
}

type EmsConfigApiFormIdReq struct {
	Id int64 `form:"id"`
}

type EmsConfigApiFormIdsReq struct {
	Ids []int64 `form:"ids"`
}

type EmsConfigApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type EmsConfigApiJsonIdsReq struct {
	Ids []int64 `json:"ids"`
}

type EmsConfigApiOKResp struct {
}

type EmsConfigCommonQueryListResp struct {
	List     []ModelEmsConfig `json:"list"`
	Total    int64            `json:"total"`
	Page     int32            `json:"page"`
	PageSize int32            `json:"page_size"`
}

type EmsConfigCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int16  `json:"status,optional"`
}

type EmsInitReq struct {
	Key     string `json:"key,optional"`
	Service string `json:"service"`
	Type    string `json:"type"`
	Mail    string `json:"mail"`
}

type EmsInitResp struct {
	RequestId string `json:"request_id"`
	Status    string `json:"status"`
}

type EmsVerifyReq struct {
	Service    string `json:"service"`
	Type       string `json:"type"`
	Mail       string `json:"mail"`
	VerifyCode string `json:"verify_code"`
}

type EmsVerifyResp struct {
	Result  bool   `json:"result"`
	Code    string `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}

type GetIpMyReq struct {
}

type GetIpQueryReq struct {
	Ip string `form:"ip"`
}

type GetIpQueryResp struct {
	IP        string `json:"ip"`         // IP地址
	IPHash    string `json:"ip_hash"`    // IPHash
	Port      string `json:"port"`       // Port
	UserAgent string `json:"user_agent"` // UserAgent
	CityId    int64  `json:"city_id"`    // CityId
	Country   string `json:"country"`    // Country
	Region    string `json:"region"`     // Region
	Province  string `json:"province"`   // Province
	City      string `json:"city"`       // City
	ISP       string `json:"isp"`        // ISP
}

type HealthzResp struct {
}

type KmsAkcCreateKeychainReq struct {
	KeyType string `json:"key_type,options=RSA|EC|OKP|OCT"`
	Name    string `json:"name"`
	Alg     string `json:"alg,options=ES256|ES256K|ES384|ES512|EdDSA|PS256|PS384|PS512|RS256|RS384|RS512"`
	RsaBits int    `json:"rsa_bits,optional,options=1024|2048|3072|4096|8192"`
}

type KmsAkcCreateKeychainResp struct {
	Id        uint32   `json:"id"`
	Jwk       ModelJwk `json:"jwk"`
	PublicKey string   `json:"public_key"`
}

type KmsAkcGetKeychainPublicKeyReq struct {
	Name string `json:"name,optional"`
	Kid  string `json:"kid,optional"`
}

type KmsAkcGetKeychainPublicKeyResp struct {
	PublicKey string   `json:"public_key"`
	Jwk       ModelJwk `json:"jwk"`
}

type KmsAkcSignReq struct {
	Name        string `json:"name,optional"`
	SignContent string `json:"sign_content"`
	Kid         string `json:"kid,optional"`
}

type KmsAkcSignResp struct {
	Name string `json:"name,optional"`
	Sign string `json:"sign"`
}

type KmsAkcVerifyReq struct {
	Name string `json:"name,optional"`
	Sign string `json:"sign"`
	Kid  string `json:"kid,optional"`
}

type KmsAkcVerifyResp struct {
	Name   string `json:"name"`
	Verify bool   `json:"verify"`
}

type KmsSkcBatchDecryptReq struct {
	Data map[string]KmsSkcBatchDecryptReqItem `json:"data"`
}

type KmsSkcBatchDecryptReqItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcBatchDecryptResp struct {
	Result map[string]KmsSkcBatchDecryptRespItem `json:"result"`
}

type KmsSkcBatchDecryptRespItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
	Status   string `json:"status"`
}

type KmsSkcBatchEncryptReq struct {
	Data map[string]KmsSkcBatchEncryptReqItem `json:"data"`
}

type KmsSkcBatchEncryptReqItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcBatchEncryptResp struct {
	Result map[string]KmsSkcBatchEncryptRespItem `json:"result"`
}

type KmsSkcBatchEncryptRespItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
	Status   string `json:"status"`
}

type KmsSkcCompareItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcCompareReq struct {
	List []KmsSkcCompareItem `json:"list"`
}

type KmsSkcCompareResp struct {
	Status      string                      `json:"status"`
	CompareData bool                        `json:"compare_data"`
	List        []KmsSkcCompareRespDataItem `json:"list"`
}

type KmsSkcCompareRespData struct {
	Status      string                      `json:"status"`
	CompareData bool                        `json:"compare_data"`
	List        []KmsSkcCompareRespDataItem `json:"list"`
}

type KmsSkcCompareRespDataItem struct {
	Status   string `json:"status"`
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcCreateKeychainReq struct {
	Algorithm string `json:"algorithm,options=AES-128-GCM|AES-192-GCM|AES-256-GCM|AES-128-CBC|AES-192-CBC|AES-256-CBC|AES-128-CCM|AES-192-CCM|AES-256-CCM|AES-128-CTR|AES-192-CTR|AES-256-CTR"`
	Name      string `json:"name"`
}

type KmsSkcCreateKeychainResp struct {
	Status string `json:"status"`
	Name   string `json:"name"`
}

type KmsSkcDecryptReq struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcDecryptResp struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcEncryptReq struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data,optional"`
}

type KmsSkcEncryptResp struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type ModelBucketConfig struct {
	Id            int64  `json:"id"`
	CreatedAtUnix int64  `json:"created_at_unix,optional"`
	UpdatedAtUnix int64  `json:"updated_at_unix,optional"`
	IsDefault     bool   `json:"is_default,optional"`
	Status        int16  `json:"status,optional"`
	Name          string `json:"name"`
	StorageType   string `json:"storage_type,options=minio|cos|oss|s3|obs"`
	CredentialID  int64  `json:"credential_id"`
	BucketName    string `json:"bucket_name"`
	Region        string `json:"region"`
	Prefix        string `json:"prefix"`
	Endpoint      string `json:"endpoint"`
	PublicDomain  string `json:"public_domain"`
	Remark        string `json:"remark"`
}

type ModelCaptchaConfig struct {
	Id            int64   `json:"id"`
	CreatedAtUnix int64   `json:"created_at_unix,optional"`
	UpdatedAtUnix int64   `json:"updated_at_unix,optional"`
	IsDefault     bool    `json:"is_default,optional"`
	Status        int16   `json:"status,optional"`
	Name          string  `json:"name"`
	DotCount      int32   `json:"dot_count"`
	MaxSkew       float64 `json:"max_skew"`
	KeyLong       int32   `json:"key_long"`
	ImgWidth      int32   `json:"img_width"`
	ImgHeight     int32   `json:"img_height"`
}

type ModelClient struct {
	IP              string `json:"ip"`                // IP地址
	IPHash          string `json:"ip_hash"`           // IPHash
	Port            string `json:"port"`              // Port
	UserAgent       string `json:"user_agent"`        // UserAgent
	CityId          int64  `json:"city_id"`           // CityId
	Country         string `json:"country"`           // Country
	Region          string `json:"region"`            // Region
	Province        string `json:"province"`          // Province
	City            string `json:"city"`              // City
	ISP             string `json:"isp"`               // ISP
	UserAgentFamily string `json:"user_agent_family"` // UserAgentFamily
	UserAgentMajor  string `json:"user_agent_major"`  // UserAgentMajor
	UserAgentMinor  string `json:"user_agent_minor"`  // UserAgentMinor
	UserAgentPatch  string `json:"user_agent_patch"`  // UserAgentPatch
	OsFamily        string `json:"os_family"`         // OsFamily
	OsMajor         string `json:"os_major"`          // OsMajor
	OsMinor         string `json:"os_minor"`          // OsMinor
	OsPatch         string `json:"os_patch"`          // OsPatch
	OsPatchMinor    string `json:"os_patch_minor"`    // OsPatchMinor
	DeviceFamily    string `json:"device_family"`     // DeviceFamily
	DeviceBrand     string `json:"device_brand"`      // DeviceBrand
	DeviceModel     string `json:"device_model"`      // DeviceModel
}

type ModelCode struct {
	Code string `json:"code"`
	Num  int32  `json:"num"`
	Msg  string `json:"msg"`
}

type ModelCredential struct {
	Id              int64  `json:"id"`
	CreatedAtUnix   int64  `json:"created_at_unix,optional"`
	UpdatedAtUnix   int64  `json:"updated_at_unix,optional"`
	IsDefault       bool   `json:"is_default,optional"`
	Status          int16  `json:"status,optional"`
	Name            string `json:"name"`
	CredentialType  string `json:"credential_type"`
	AccessKeyID     string `json:"access_key_id"`
	SecretAccessKey string `json:"secret_access_key"`
	Remark          string `json:"remark"`
	DefaultRegion   string `json:"default_region"`
	AppID           string `json:"app_id"`
	Endpoint        string `json:"endpoint"`
}

type ModelEmsConfig struct {
	Id            int64  `json:"id"`
	CreatedAtUnix int64  `json:"created_at_unix,optional"`
	UpdatedAtUnix int64  `json:"updated_at_unix,optional"`
	IsDefault     bool   `json:"is_default,optional"`
	Status        int16  `json:"status,optional"`
	Name          string `json:"name"`
	CredentialID  int64  `json:"credential_id"`
	SenderName    string `json:"sender_name"`
	Endpoint      string `json:"endpoint"`
	Port          int32  `json:"port"`
	Protocol      string `json:"protocol"`
	Remark        string `json:"remark"`
}

type ModelJwk struct {
	Kty string `json:"kty,omitempty"`
	Alg string `json:"alg,omitempty"`
	Use string `json:"use,omitempty"`
	Kid string `json:"kid,omitempty"`
	N   string `json:"n,omitempty"`
	E   string `json:"e,omitempty"`
	X   string `json:"x,omitempty"`
	Y   string `json:"y,omitempty"`
	Crv string `json:"crv,omitempty"`
}

type ModelSmsConfig struct {
	Id            int64  `json:"id"`
	CreatedAtUnix int64  `json:"created_at_unix,optional"`
	UpdatedAtUnix int64  `json:"updated_at_unix,optional"`
	IsDefault     bool   `json:"is_default,optional"`
	Status        int16  `json:"status,optional"`
	Name          string `json:"name"`
	CredentialID  int64  `json:"credential_id"`
	Endpoint      string `json:"endpoint"`
	Template      string `json:"template"`
	SignName      string `json:"sign_name"`
	ParamsStr     string `json:"params_str"`
	Remark        string `json:"remark"`
}

type ModelWechatConfig struct {
	Id            int64  `json:"id"`
	CreatedAtUnix int64  `json:"created_at_unix,optional"`
	UpdatedAtUnix int64  `json:"updated_at_unix,optional"`
	IsDefault     bool   `json:"is_default,optional"`
	Status        int16  `json:"status,optional"`
	Name          string `json:"name"`
	AppType       string `json:"app_type,options=official|mini_app"`
	CredentialID  int64  `json:"credential_id"`
	GhId          string `json:"gh_id"`
	AppName       string `json:"app_name"`
	Remark        string `json:"remark"`
}

type ModelZone struct {
	Label string `json:"label"`
	Code  string `json:"code"`
	Area  string `json:"area"`
}

type NotFoundReq struct {
}

type NotFoundResp struct {
}

type OkResp struct {
}

type PublicGetIpReq struct {
}

type PublicGetIpResp struct {
	Ip string `json:"ip"` // note: 返回自身ip
}

type RemoveSomePolicyReq struct {
	Subject string `json:"subject"`
	Object  string `json:"object"`
	Action  string `json:"action"`
}

type SasPresignerGetObjectReq struct {
	Name string `json:"name,optional"`
	Path string `json:"path"`
}

type SasPresignerGetObjectResp struct {
	Url    string `json:"url"`
	Method string `json:"method"`
}

type SasPresignerHeadObjectReq struct {
	Name string `json:"name,optional"`
	Path string `json:"path"`
}

type SasPresignerHeadObjectResp struct {
	Url    string `json:"url"`
	Method string `json:"method"`
}

type SasPresignerUploadReq struct {
	Name string `json:"name,optional"`
	Path string `json:"path"`
}

type SasPresignerUploadResp struct {
	Url    string            `json:"url"`
	Fields map[string]string `json:"fields"`
}

type SasQueryBucketReq struct {
	Name string `json:"name,optional"`
}

type SasQueryBucketResp struct {
	Name         string `json:"name"`
	Prefix       string `json:"prefix"`
	Region       string `json:"region"`
	Endpoint     string `json:"endpoint"`
	PublicDomain string `json:"public_domain"`
	Remark       string `json:"remark"`
}

type SmsConfigApiCreateResp struct {
	Id int64 `json:"id"`
}

type SmsConfigApiFormIdReq struct {
	Id int64 `form:"id"`
}

type SmsConfigApiFormIdsReq struct {
	Ids []int64 `form:"ids"`
}

type SmsConfigApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type SmsConfigApiJsonIdsReq struct {
	Ids []int64 `json:"ids"`
}

type SmsConfigApiOKResp struct {
}

type SmsConfigCommonQueryListResp struct {
	List     []ModelSmsConfig `json:"list"`
	Total    int64            `json:"total"`
	Page     int32            `json:"page"`
	PageSize int32            `json:"page_size"`
}

type SmsConfigCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int16  `json:"status,optional"`
}

type SmsInitReq struct {
	Key     string `json:"key,optional"`
	Service string `json:"service"`
	Type    string `json:"type"`
	Zone    string `json:"zone"`
	Phone   string `json:"phone"`
}

type SmsInitResp struct {
	RequestId string `json:"request_id"`
	Status    string `json:"status"`
}

type SmsVerifyReq struct {
	Service    string `json:"service"`
	Type       string `json:"type"`
	Zone       string `json:"zone"`
	Phone      string `json:"phone"`
	VerifyCode string `json:"verify_code"`
}

type SmsVerifyResp struct {
	Result  bool   `json:"result"`
	Code    string `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}

type TaskQueueAnchoredJobAddReq struct {
	Name          string `json:"name"`                                                    // 任务名称
	AnchorTime    string `json:"anchor_time"`                                             // 锚定时间
	IntervalType  string `json:"interval_type,options=second|minute|hour|day|month|year"` // 循环时长类型
	IntervalValue int32  `json:"interval_value"`                                          // 循环时长数量
	Webhook       string `json:"webhook"`                                                 // 回调地址
	Params        string `json:"params"`                                                  // 回调参数
	Secret        string `json:"secret"`                                                  // 回调密钥
}

type TaskQueueAnchoredJobAddResp struct {
	Id int64 `json:"id"`
}

type TaskQueueAnchoredJobRemoveReq struct {
	Id int64 `json:"id"`
}

type TaskQueueAnchoredJobRemoveResp struct {
}

type TaskQueueDelayedJobAddReq struct {
	Name          string `json:"name"`            // 任务名称
	ExecuteAt     string `json:"execute_at"`      // 任务执行时间
	MaxRetryCount int32  `json:"max_retry_count"` // 最大执行时间
	Webhook       string `json:"webhook"`         // 回调地址
	Params        string `json:"params"`          // 回调参数
	Secret        string `json:"secret"`          // 回调密钥
}

type TaskQueueDelayedJobAddResp struct {
	Id int64 `json:"id"`
}

type TaskQueueDelayedJobCancelReq struct {
	Id int64 `json:"id"`
}

type TaskQueueDelayedJobCancelResp struct {
}

type TaskQueuePeriodicJobAddReq struct {
	Name    string `json:"name"`    // 任务名称
	Spec    string `json:"spec"`    // cron表达式
	Webhook string `json:"webhook"` // 回调地址
	Params  string `json:"params"`  // 回调参数
	Secret  string `json:"secret"`  // 回调密钥
}

type TaskQueuePeriodicJobAddResp struct {
	Id int64 `json:"id"`
}

type TaskQueuePeriodicJobRemoveReq struct {
	Id int64 `json:"id"`
}

type TaskQueuePeriodicJobRemoveResp struct {
}

type TpasWechatJobWebhookReq struct {
	Payload string `json:"payload"`
}

type TpasWechatJobWebhookResp struct {
}

type WechatConfigApiCreateResp struct {
	Id int64 `json:"id"`
}

type WechatConfigApiFormIdReq struct {
	Id int64 `form:"id"`
}

type WechatConfigApiFormIdsReq struct {
	Ids []int64 `form:"ids"`
}

type WechatConfigApiJsonIdReq struct {
	Id uint32 `json:"id"`
}

type WechatConfigApiJsonIdsReq struct {
	Ids []int64 `json:"ids"`
}

type WechatConfigApiOKResp struct {
}

type WechatConfigCommonQueryListResp struct {
	List     []ModelWechatConfig `json:"list"`
	Total    int64               `json:"total"`
	Page     int32               `json:"page"`
	PageSize int32               `json:"page_size"`
}

type WechatConfigCommonSearchParams struct {
	Page           int32  `json:"page,optional"`
	PageSize       int32  `json:"page_size,optional"`
	StartCreatedAt int64  `json:"start_created_at,optional"`
	EndCreatedAt   int64  `json:"end_created_at,optional"`
	Keyword        string `json:"keyword,optional"`
	Status         int16  `json:"status,optional"`
}

type WechatForceRefreshOffiaccountAccessTokenReq struct {
	Key string `json:"key"`
}

type WechatForceRefreshOffiaccountAccessTokenResp struct {
}

type WechatOffiaccountCode2TokenReq struct {
	Key  string `json:"key,optional"`
	Code string `json:"code"`
}

type WechatOffiaccountCode2TokenResp struct {
	AccessToken    string `json:"access_token"`
	ExpiresIn      int64  `json:"expires_in"`
	RefreshToken   string `json:"refresh_token"`
	Openid         string `json:"openid"`
	Scope          string `json:"scope"`
	IsSnapshotuser int32  `json:"is_snapshotuser"`
	Unionid        string `json:"unionid"`
	Errcode        int32  `json:"errcode,omitempty"`
	Errmsg         string `json:"errmsg,omitempty"`
}

type WechatOffiaccountGenRedirectUrlReq struct {
	Key         string `json:"key,optional"`
	Scope       string `json:"scope,options=snsapi_base|snsapi_userinfo"`
	RedirectUri string `json:"redirect_uri"`
	State       string `json:"state"`
}

type WechatOffiaccountGenRedirectUrlResp struct {
	Scope string `json:"scope"`
	Url   string `json:"url"`
	State string `json:"state"`
}

type WechatOffiaccountGenShareConfigReq struct {
	Key       string   `json:"key,optional"`
	Debug     bool     `json:"debug"`
	ShareLink string   `json:"share_link"`
	JsApiList []string `json:"js_api_list"`
}

type WechatOffiaccountGenShareConfigResp struct {
	Debug     bool     `json:"debug"`
	AppId     string   `json:"app_id"`
	Timestamp int64    `json:"timestamp"`
	NonceStr  string   `json:"nonce_str"`
	Signature string   `json:"signature"`
	JsApiList []string `json:"js_api_list"`
}

type WechatOffiaccountGetAccessTokenReq struct {
	Key string `json:"key,optional"`
}

type WechatOffiaccountGetAccessTokenResp struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
}

type WechatOffiaccountGetJsApiTicketReq struct {
	Key string `json:"key,optional"`
}

type WechatOffiaccountGetJsApiTicketResp struct {
	Ticket    string `json:"ticket"`
	ExpiresIn int64  `json:"expires_in"`
}

type ZonesReq struct {
	Lang string `form:"lang,optional" url:"lang"`
}

type ZonesResp struct {
	List     []ModelZone `json:"list"`
	Total    int64       `json:"total"`
	Page     int32       `json:"page"`
	PageSize int32       `json:"page_size"`
}
